server:
  port: 8080

spring:
  r2dbc:
    url: r2dbcs:mysql://bugfree.ixiaochuan.cn:23306/bugfree?sslMode=DISABLED
    username: bugfree
    password: bugfree
    pool:
      initialSize: 2
      maxSize: 10